spring.application.name=PlanIT
spring.datasource.url=jdbc:postgresql://localhost:5432/PlanIT
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

server.servlet.context-path=/api/v2.0


# Hibernate / JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth= true
spring.mail.properties.mail.smtp.starttls.enable= true
spring.mail.properties.mail.smtp.ssl.trust= smtp.gmail.com


app.base-url=${APP_BASE_URL:http://localhost:8080}
app.mail.from=${MAIL_USERNAME}

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

